---

- hosts: server
  become: yes
  tasks:
    - name: install needed software
      package:
        name: openssl-devel
      when: ansible_os_family == 'RedHat'

    - name: install needed software
      package:
        name:
          - libssl-dev
          - libcurl4-openssl-dev
          - python-setuptools
      when: ansible_os_family == 'Debian'

    - name: clone sentinel5dl repository
      become_user: emissions-api
      git:
        repo: https://github.com/emissions-api/sentinel5dl.git
        dest: /opt/emissions-api/sentinel5dl/

    - name: install requirements
      pip:
        requirements: /opt/emissions-api/sentinel5dl/requirements.txt
        virtualenv: /opt/emissions-api/sentinel5dl/venv/
        virtualenv_command: /usr/bin/python3 -m venv
      environment:
        PYCURL_SSL_LIBRARY: openssl

    - name: Ensures autoupdate dir exists
      file:
        path: /opt/emissions-api/autoupdate/
        state: directory

    - name: install autoupdate script
      copy:
        dest: /opt/emissions-api/autoupdate/autoupdate
        src: autoupdate/autoupdate
        mode: 0755

    - name: install systemd files
      copy:
        dest: /etc/systemd/system/
        src: autoupdate/{{ item }}
        mode: 0644
      loop:
        - emissionsapi-import.service
        - emissionsapi-import.timer
      notify:
        - reload systemd

    - name: enable systemd timer
      service:
        name: emissionsapi-import.timer
        enabled: yes
        state: started

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes
