---

- hosts: server
  become: yes
  vars_files:
    - secret-vars.yml
  tasks:
    - name: install needed software
      package:
        name:
          - git
          - python3

      when: ansible_os_family == 'Debian'
    - name: install RedHat specific software
      package:
        name:
          - cmake3
          - gcc
          - make
          - postgresql-devel
          - python3-devel
          - openssl-devel
      when: ansible_os_family == 'RedHat'

    - name: install Debian specific software
      package:
        name:
          - python3-venv
          - python3-dev
          - build-essential
          - cmake
          - libpq-dev
          - libssl-dev
          - libcurl4-openssl-dev
      when: ansible_os_family == 'Debian'

    - name: create Emissions-API user
      user:
        name: emissions-api
        system: yes
        home: /opt/emissions-api

    - name: clone Emissions-API repository
      become_user: emissions-api
      git:
        repo: https://github.com/emissions-api/emissions-api.git
        dest: /opt/emissions-api/emissions-api/

    # Workaround for python h3.
    # It is using cmake > 3.1 which is called cmake3 on Amazon Linux 2
    - name: link cmake to cmake3
      file:
        state: link
        path: /bin/cmake
        src: /bin/cmake3
      when: ansible_distribution == "Amazon"

    - name: install requirements
      pip:
        requirements: /opt/emissions-api/emissions-api/requirements.txt
        virtualenv: /opt/emissions-api/venv/
        virtualenv_command: /usr/bin/python3 -m venv
      environment:
        PYCURL_SSL_LIBRARY: openssl

    - name: install Emissions-API config file
      template:
        dest: /opt/emissions-api/emissions-api/emissionsapi.yml
        src: emissions-api/emissionsapi.yml.j2
        force: yes
        owner: emissions-api
        group: emissions-api
        mode: 0600
      notify:
        restart emissionsapi-web

    - name: install systemd files
      copy:
        dest: /etc/systemd/system/
        src: emissions-api/{{ item }}
        force: yes
        mode: 0644
      loop:
        - emissionsapi-import.service
        - emissionsapi-import.timer
      notify:
        - reload systemd

    - name: install Emissions-API service file
      copy:
        dest: /etc/systemd/system/
        src: emissions-api/emissionsapi-web.service
        force: yes
        mode: 0644
      notify:
        - reload systemd
        - restart emissionsapi-web

    - name: run Emissions-API now and on boot
      service:
        name: '{{ item }}'
        enabled: yes
        state: started
      with_items:
        - emissionsapi-web
        - emissionsapi-import.timer

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart emissionsapi-web
      service:
        name: emissionsapi-web
        state: restarted
