---

- hosts: server
  become: yes
  vars_files:
    - secret-vars.yml
  tasks:
    - name: install needed software
      apt:
        name: msmtp-mta

    - name: copy mail config file
      copy:
        content: |
            # Set default values for all following accounts.
            defaults
            auth           on
            tls            on
            tls_starttls   off
            tls_trust_file /etc/ssl/certs/ca-certificates.crt
            syslog         on

            # mailbox
            account        mailbox
            host           smtp.mailbox.org
            port           465
            from           info@emissions-api.org
            user           info@emissions-api.org
            password       {{ mail_password }}

            # Set a default account
            account default : mailbox
        dest: /etc/msmtprc
        mode: 0600