---

- hosts: server
  become: yes
  tasks:
    - name: install needed software
      apt:
        name:
          - nginx
          - certbot
          - python-certbot-nginx

    - name: remove default site
      file:
        state: absent
        path: /etc/nginx/sites-enabled/default
      notify: reload nginx

    - name: create certificate for {{ domain_name }}
      command: certbot certonly --domain {{ domain_name }} --nginx --agree-tos -m info@emissions-api.org
      args:
        creates: /etc/letsencrypt/live/{{ domain_name }}/cert.pem
      notify: reload nginx

    - name: install diffie hellmann paramter
      copy:
        src: nginx/dhparam.pem
        dest: /etc/nginx/dhparam.pem
        force: yes
      notify: reload nginx

    - name: install config file for {{ domain_name }}
      template:
        dest: /etc/nginx/sites-available/{{ domain_name }}.conf
        src: nginx/server.conf
        force: yes
      notify: reload nginx

    - name: enable {{ domain_name }}
      file:
        state: link
        src: /etc/nginx/sites-available/{{ domain_name }}.conf
        dest: /etc/nginx/sites-enabled/{{ domain_name }}.conf
      notify: reload nginx

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
