---

- hosts: server
  vars:
    admins:
      - sven
      - hendrik
      - lars
      - simon

  tasks:
    - name: install base tools
      become: true
      package:
        name:
          - vim
          - zsh
          - htop
          - iotop
          - mc

    - name: create admin users
      become: true
      user:
        name: '{{ item }}'
        groups: wheel
        append: true
      loop: '{{ admins }}'

    - name: set up admin authorized keys
      become: true
      authorized_key:
        user: '{{ item }}'
        state: present
        key: "{{ lookup('file', 'pub-keys/{{ item }}.pub') }}"
      loop: '{{ admins }}'

    - name: allow to sudo without a password
      become: true
      copy:
        dest: /etc/sudoers.d/password-less-sudo
        mode: 0600
        content: "%wheel ALL=(ALL) NOPASSWD: ALL"
        force: yes
